
FROM node:20-alpine AS build
WORKDIR /project/frontend
COPY ../frontend/package.json ./
COPY ../frontend/package-lock.json ./
COPY ../frontend /project/frontend
RUN npm install

RUN npm run build

FROM nginx
EXPOSE 3000
COPY ../frontend/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /project/frontend/dist  /usr/share/nginx/html

