
FROM node:20-alpine
WORKDIR /project/frontend
COPY package.json ./
COPY package-lock.json ./
RUN npm run build

FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /project/frontend/build  /usr/share/nginx/html

