version: '3.8'

services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /project/frontend/node_modules
      - ./frontend:/project/frontend
    stdin_open: true
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks: 
     - app_network 
  nginx:
    build:
      context: ./nginx/dev
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      -  backend_main
      -  backend_chat1
      -  backend_chat2
      -  backend_chat3
    container_name: nginx
    networks: 
     - app_network

  backend_main:
    build:
      context: ./rand_chat_main_api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis-master-1
    container_name: backend_main
    networks: 
     - app_network
  backend_chat1:
    build:
      context: ./rand_chat_chatserver_api
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - mysql
      - redis-master-1
    container_name: backend_chat1
    networks: 
     - app_network
  backend_chat2:
    build:
      context: ./rand_chat_chatserver_api
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    container_name: backend_chat2
    depends_on:
      - mysql
      - redis-master-1
    networks: 
     - app_network 
  backend_chat3:
    build:
      context: ./rand_chat_chatserver_api
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    container_name: backend_chat3
    depends_on:
      - mysql
      - redis-master-1
    networks: 
     - app_network
  mysql:
    image: mysql:8.0.17
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
    ports:
      - "3307:3306"
    volumes:
      - ./mysqlevn/masterdb:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks: 
     - app_network  
  redis-master-1:
    image: redis:6.2
    ports:
      - "6379:6379"
    container_name: redis-master-1  
    networks: 
     - app_network

networks:
  app_network:
    driver: bridge    
   
  

  