version: '3.8'

services:
  backend_match1:
    build:
      context: ./backend
      dockerfile: Dockerfile-match-it-test
    ports:
      - "8081:8080"
    container_name: backend_match1
    environment: 
      - INSTANCE_ID=server1 
      - SPRING_PROFILES_ACTIVE=dev
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - S3_REGION=${S3_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
    ports:
      - "3307:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  redis-master-1:
    image: redis:alpine
    ports:
      - "6379:6379"
    container_name: redis-master-1  
 


  

  