spring:
  datasource:
    url: jdbc:mysql://localhost:3307/rand
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    mapper-locations: classpath:mapper/*.xml    # XML ?? ??? ??
#    type-aliases-package: com.example.demo.model
    configuration:
      map-underscore-to-camel-case: true

  redis:
    # ?? Redis ?? ??
    host: redis-cache
    port: 6379

    redis-chat:
      host: redis-chat
      port: 6382

    redis-token:
      host: redis-token
      port: 6384

    redis-persistent:
      host: redis-persistent
      port: 6380

    redis-persistent-replica:
      host: redis-persistent-replica
      port: 6381

