spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3307/rand
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    mapper-locations: classpath:mapper/*.xml    # XML ?? ??? ??
    type-aliases-package: rand.api.*
    configuration:
      map-underscore-to-camel-case: true

  redis:
    # ?? Redis ?? ??
    host: redis-cache
    port: 6379

    redis-chat:
      host: redis-chat
      port: 6382
    redis-chat-replica:
      host: redis-chat-replica
      port: 6383

    redis-token:
      host: redis-token
      port: 6384

    redis-token-replica:
      host: redis-token-replica
      port: 6385

    redis-persistent:
      host: redis-persistent
      port: 6380

    redis-persistent-replica:
      host: redis-persistent-replica
      port: 6381
  mail:
    host: smtp.gmail.com
    port: 587
    username: gimyongjun414@gmail.com
    password: olix wufv ehek kiyb   # 환경 변수로 비밀번호 설정
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

