name: BACKEND-MATCH-RELEASE

on:
  push:
    tags:
      - 'bd.match.v*.*.*'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # JDK 분포 설정

      - name: Set environment variables
        run: |
          echo "S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}" >> $GITHUB_ENV
          echo "S3_REGION=${{ secrets.S3_REGION }}" >> $GITHUB_ENV
          echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # - name: Run mysql
      #   run: |
      #      docker compose -f ./docker-compose-it-test.yml up -d mysql

      # - name: Run Redis
      #   run: |
      #      docker compose -f ./docker-compose-it-test.yml up -d redis-master-1    

      # - name: Wait for DB
      #   run: |
      #     sleep 10  # 적절한 대기 시간 설정

      # - name: Run IT Tests
      #   run: |
      #     docker-compose -f ./docker-compose-it-test.yml up backend_match1    # 컨테이너 빌드 및 실행

      - name: Extract tag name
        run: |
          echo "Full reference: $GITHUB_REF"  # 전체 참조 정보 출력
          TAG_NAME=$(echo $GITHUB_REF | sed 's/refs\/tags\///')  # "refs/tags/v1.0.0"에서 "v1.0.0" 추출
          echo "Tag name: $TAG_NAME"  # 추출된 태그 이름 출력    
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV  # 환경 변수로 설정

      - name: Login Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
      # 이미지 빌드
      - name: BACKEND-MATCH Image Build
        run: |
          docker build -f ./backend/Dockerfile-match-deploy -t kimyong120413/randchatbackendmatch:$TAG_NAME .
          docker push kimyong120413/randchatbackendmatch:$TAG_NAME
