name: BEFORE MERGE DEVELOP BRANCH CONTAINS UNIT TEST [CI]

on:
  pull_request:
    branches:
      - develop  # develop 브랜치에 대한 PR 생성 시 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          clean: false  # 클린 비활성화
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # JDK 분포 설정

      - name: Run Unit Tests
        run: |
          docker-compose -f ./docker-compose-dev.yml up --build --abort-on-container-exit  # 컨테이너 빌드 및 실행
          
