name: BEFORE MERGE DEVELOP BRANCH CONTAINS UNIT TEST [CI]

on:
  pull_request:
    branches:
      - develop  # develop 브랜치에 대한 PR 생성 시 트리거

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          clean: false  # 클린 비활성화
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # JDK 분포 설정

      - name: Set environment variables
        run: |
         echo "S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}" >> $GITHUB_ENV
         echo "S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}" >> $GITHUB_ENV
         echo "S3_REGION=${{ secrets.S3_REGION }}" >> $GITHUB_ENV
         echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
         sudo apt-get update
         sudo apt-get install -y docker-compose

      - name: Run Unit Tests
        run: |
          docker-compose -f ./docker-compose-unit-test.yml up --build --abort-on-container-exit  # 컨테이너 빌드 및 실행
          
